version: 2

project_name: programmator

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: programmator
    binary: programmator
    main: ./cmd/programmator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: programmator
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: git
  format: "{{ .Message }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
